#!/usr/bin/python

# Copy file to clipboard
#toolsdir=$( readlink -f "$( dirname "$BASH_SOURCE" )" )

#java -classpath $toolsdir copyFile $1 &

import pygtk
pygtk.require('2.0')
import gtk
import sys

f = open(sys.argv[1],'rb')

# get the clipboard
clipboard = gtk.clipboard_get()

# read the clipboard text data. you can also read image and
# rich text clipboard data with the
# wait_for_image and wait_for_rich_text methods.
#text = clipboard.wait_for_text()

# set the clipboard text data
clipboard.set_text(f.read())

# make our data available to other applications
clipboard.store()
