#!/bin/bash

# Compile current problem with GNU C++ Compiler 
problem=${PWD:(-1):1}

rm *.class
echo Compiling problem $problem with Java Compiler
echo "javac -sourcepath $toolsdir/source *Executer.java"
javac -sourcepath $toolsdir/source:. -d . *Executer.java
cls=$(getexclass)

echo "#!/bin/sh
java $cls" > $problem
chmod a+x $problem
